### ISSUE TITLE
Random console errors.

### ISSUE THREAD

**Issue by godsyn** [rutgerkok/BlockLocker#1]
If i find out how to reproduce my issue, I'll update the ticket. This is occasionally appearing in the console:

> [09:01:51 ERROR]: Could not pass event BlockRedstoneEvent to BlockLocker v1.1.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.BlockDoor.doPhysics(BlockDoor.java:173) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.World.d(World.java:579) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.World.applyPhysics(World.java:528) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.e(BlockPressurePlateAbstract.java:151) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:120) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.BlockPressurePlateAbstract.b(BlockPressurePlateAbstract.java:82) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:653) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor230.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
        at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.call(NMSAccessor.java:125) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.getSecretData(NMSAccessor.java:252) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.getJsonData(NMSAccessor.java:231) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.SignParserImpl.parseSign(SignParserImpl.java:121) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.blockfinder.BlockFinder.findAttachedSigns(BlockFinder.java:77) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.blockfinder.BlockFinder.findAttachedSigns(BlockFinder.java:100) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.ProtectionFinderImpl.findProtectionForProtectionBlock(ProtectionFinderImpl.java:188) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.ProtectionFinderImpl.findProtectionForBlock(ProtectionFinderImpl.java:135) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.ProtectionFinderImpl.findProtection(ProtectionFinderImpl.java:122) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.ProtectionFinderImpl.findProtection(ProtectionFinderImpl.java:106) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.event.EventListener.isProtectedForRedstone(EventListener.java:38) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.event.BlockDestroyListener.onRedstone(BlockDestroyListener.java:150) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-3f3c65f]
        ... 16 more

**Comment by rutgerkok** [comment]
I added a null check. This should fix the issue, but as I'm not able to reproduce it, I'm not sure.

Would you be willing to test this version?

[Download 1.1.3-SNAPSHOT](https://dl.dropboxusercontent.com/u/23288978/BlockLocker.jar)

**Comment by godsyn** [comment]
Downloaded and loaded. Will update if the issue returns.

**Comment by godsyn** [comment]
4 days of testing without console errors. Thank you.

**Comment by rutgerkok** [comment]
That's great to hear!
