### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by slvlr** [rutgerkok/BlockLocker#101]
This is in my config, how do I fix it? 

>.... [00:16:16 ERROR]: Could not pass event BlockPlaceEvent to BlockLocker v1.9.2
java.lang.NoClassDefFoundError: com/palmergames/bukkit/towny/object/TownyUniverse
at nl.rutgerkok.blocklocker.impl.location.TownyLocationChecker.checkLocation(TownyLocationChecker.java:32) ~[?:?]
at nl.rutgerkok.blocklocker.location.CombinedLocationChecker.checkLocation(CombinedLocationChecker.java:33) ~[?:?]
at nl.rutgerkok.blocklocker.location.LocationChecker.checkLocationAndPermission(LocationChecker.java:45) ~[?:?]
at nl.rutgerkok.blocklocker.impl.event.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:85) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-468]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:377) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:280) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:533) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[?:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by slvlr** [comment]
I reported it to Towny and they said: BlockLocker needs to update to not use the API we deprecated in 2019

**Comment by rutgerkok** [comment]
Should be fixed in build 24 - download at https://ci.codemc.io/job/rutgerkok/job/BlockLocker/24/

**Comment by slvlr** [comment]
Thank you.
