### ISSUE TITLE
Error fetching UUID: too many requests

### ISSUE THREAD

**Issue by LogGits** [rutgerkok/BlockLocker#19]
```
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_201]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_201]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler$MojangWeb.uuidLookup(UUIDHandler.java:113) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.fetchUniqueIdsAtMojang(UUIDHandler.java:408) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.lambda$0(UUIDHandler.java:472) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-561]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-561]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[06:01:39] [Craft Scheduler Thread - 386/WARN]: [BlockLocker] Error fetching UUIDs
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_201]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_201]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler$MojangWeb.uuidLookup(UUIDHandler.java:113) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.fetchUniqueIdsAtMojang(UUIDHandler.java:408) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.lambda$0(UUIDHandler.java:472) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-561]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-561]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[06:01:42] [Craft Scheduler Thread - 379/WARN]: [BlockLocker] Error fetching UUIDs
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_201]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_201]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler$MojangWeb.uuidLookup(UUIDHandler.java:113) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.fetchUniqueIdsAtMojang(UUIDHandler.java:408) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.converter.UUIDHandler.lambda$0(UUIDHandler.java:472) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-561]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-561]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-561]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by rutgerkok** [comment]
`java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft`

HTTP response code 429 means "too many requests". So BlockLocker is looking up the UUID of a name too often. UUID lookups should only happen if:

* no UUID is stored yet on the sign *and*
* the player listed on the sign is offline *and*
* the UUID for that name has not been looked up earlier since the server started

Do you have another plugin on your server that is looking up UUIDs from names a lot? If not, then I'll need to find a way to let BlockLocker look up fewer UUIDs online.

**Comment by LogGits** [comment]
Yes:
```
BannerBoard*, BlockLocker, BuycraftX*, ChestShop, Citizens, CMI, CoreProtect, CrateReloaded, DiscordMinecraft*, GriefPrevention, HeadDatabase*, Jobs, LiteBans, LuckPerms, Marriage*, mcMMO, ProtocolLib*, StackMob, SuperTrails*, Vault*, Votifier, VotingPlugin, WorldEdit, WorldGuard
```

Maybe if the try catch if the error occurs, if it does then just don't add the uuid to sign/return.

**Comment by eoltw** [comment]
https://gyazo.com/7f5d8acbca87bca7afa66338987a9b39

**Comment by rutgerkok** [comment]
This issue is fixed as of build 37. BlockLocker will no longer do online UUID lookups. Instead, the UUID will only be stored if the player is online. If the player is offline, no UUID will be stored until the player is online and interacts with the protection.

Download: https://ci.codemc.io/job/rutgerkok/job/BlockLocker/
