### ISSUE TITLE
A problem was discovered here, the ‘’catserver‘’server is used，Plugin not running

### ISSUE THREAD

**Issue by bulenzarathos** [rutgerkok/BlockLocker#206]
[17:20:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotMe v0.16.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-5a600445]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-5a600445]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:712) ~[CraftServer.class:git-CatServer-1.12.2-5a600445]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1669) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1470) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_421]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_421]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_421]
Caused by: java.lang.NullPointerException
        at com.worldcretornica.plotme_core.PlotMeCoreManager.getGenManager(PlotMeCoreManager.java:208) ~[?:?]
        at com.worldcretornica.plotme_core.PlotMeCoreManager.isPlotWorld(PlotMeCoreManager.java:470) ~[?:?]
        at com.worldcretornica.plotme_core.commands.CmdAuto.exec(CmdAuto.java:28) ~[?:?]
        at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:141) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-5a600445]
        ... 15 more

**Comment by rutgerkok** [comment]
I don't see BlockLocker in the stack trace, just PlotMe. I would take the issue there.
