### ISSUE TITLE
1.14.4 support

### ISSUE THREAD

**Issue by lagnat** [rutgerkok/BlockLocker#25]
I'm not very versed in the internals of MC but I believe this is the fix:

```
-        ChatModifier_getChatHoverable = getMethod(ChatModifier, "i");
+        ChatModifier_getChatHoverable = getMethod(ChatModifier, "getHoverEvent");
```

**Comment by successed** [comment]
[09:10:51] [Server thread/INFO]: [BlockLocker] Enabling BlockLocker v1.6
[09:10:52] [Server thread/ERROR]: [BlockLocker] This Minecraft version is not supported. Find another version of the plugin, if available.
java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.ChatModifier.i()
	at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.getMethod(NMSAccessor.java:61) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.<init>(NMSAccessor.java:149) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl.onEnable(BlockLockerPluginImpl.java:200) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:219) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:871) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.ChatModifier.i()
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_212]
	at nl.rutgerkok.blocklocker.impl.nms.NMSAccessor.getMethod(NMSAccessor.java:59) ~[?:?]
	... 10 more
[09:10:52] [Server thread/INFO]: [BlockLocker] Disabling BlockLocker v1.6
