### ISSUE TITLE
Could not pass event PlayerInteractEvent to BlockLocker v1.7.2

### ISSUE THREAD

**Issue by theolop** [rutgerkok/BlockLocker#57]
Hi,

Thank you for this plugin !

However, I have an issue.

This appens with Spiot 1.15.2

`[19:55:09] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BlockLocker v1.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-6de3d4b-a6f8093]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at nl.rutgerkok.blocklocker.impl.event.InteractListener.canBuildInMode(InteractListener.java:80) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.event.InteractListener.tryPlaceSign(InteractListener.java:416) ~[?:?]
	at nl.rutgerkok.blocklocker.impl.event.InteractListener.onPlayerInteract(InteractListener.java:314) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-6de3d4b-a6f8093]
	... 19 more
`

**Comment by rutgerkok** [comment]
That's strange, the game mode of the player was `null`, instead of `SURVIVAL`, `CREATIVE`, etc.

I've added some code to BlockLocker so that it can handle it now, but very strange that the game mode was null in the first place - according to the documentation of Bukkit, that shouldn't happen.

Could you test this version?

https://www.dropbox.com/s/1ghvl4rzdbtmvgf/BlockLocker.jar?dl=0

**Comment by theolop** [comment]
Hi,

Thank you very much ! It seems to work fine now.

I really don't know why it is "null"… I run Spigot with very minimal changes in config.

I just set online-mode to false, and added one plugin for auth.

Maybe this is because I changed my pseudo in a very bad way (changing in "launcher_profiles.json")…
