### ISSUE TITLE
Error during update check

### ISSUE THREAD

**Issue by Stixil** [rutgerkok/BlockLocker#86]
[00:20:38 WARN]: [BlockLocker] Error during update check (you can disable automatic updates in the config file)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://rutgerkok.nl/tools/updater/blocklocker.php?version=1.9
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.updater.UpdateChecker.checkForUpdatesSync(UpdateChecker.java:43) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.updater.Updater.updateSync(Updater.java:133) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.updater.Updater.access$100(Updater.java:22) ~[?:?]
        at nl.rutgerkok.blocklocker.impl.updater.Updater$1.run(Updater.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-294]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-294]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by rutgerkok** [comment]
Thanks, is now fixed.
