### ISSUE TITLE
When I right click the sign (without crouching) the sign is empty and anyone can access what I put it on.

### ISSUE THREAD

**Issue by PogHarvey** [rutgerkok/BlockLocker#91]
I saw this plugin on an SMP I play on a lot and wanted to implement it into the small smp that me and my friends play on. My server is a free aternos server that uses PaperMC. I can't get it to work on anything that is listed in the config file. If someone can help me fix this it would be greatly appreciated.

**Comment by rutgerkok** [comment]
Sounds like another plugin is interfering. Does it work if you shift-place a sign on a chest, and add [Private] manually?

**Comment by PogHarvey** [comment]
> Sounds like another plugin is interfering. Does it work if you shift-place a sign on a chest, and add [Private] manually?

I don't know how but I managed to get it to work when I used version 1.9 instead of 1.9.1. My server is running on 1.16.4 which is really strange

**Comment by NikitosChannel** [comment]
I have this problem too. When I put up a sign, the error is output to the console.
But if I put a sign with the shift key held down and write [Private]. Private chest created, but the chest is not protected. However, no errors are output in the console.

`[09:07:33] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to BlockLocker v1.9.1
java.lang.NullPointerException: null
at org.bukkit.craftbukkit.v1_16_R3.block.CraftSign.applyTo(CraftSign.java:79) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.craftbukkit.v1_16_R3.block.CraftSign.applyTo(CraftSign.java:13) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState.update(CraftBlockEntityState.java:147) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState.update(CraftBlockState.java:167) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState.update(CraftBlockState.java:162) ~[patched_1.16.4.jar:git-Paper-356]
at nl.rutgerkok.blocklocker.impl.SignParserImpl.saveSign(SignParserImpl.java:166) ~[?:?]
at nl.rutgerkok.blocklocker.impl.event.InteractListener.tryPlaceSign(InteractListener.java:475) ~[?:?]
at nl.rutgerkok.blocklocker.impl.event.InteractListener.onPlayerInteract(InteractListener.java:315) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-356]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-356]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-356]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-356]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]`

**Comment by rutgerkok** [comment]
Update Paper! Build 356 is broken. See https://github.com/PaperMC/Paper/issues/4975 .
